apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "aa"
  - "cf-demo-08062330"
  - "demo"
  - "manbo"
  - "privtest"
  - "probe-rt"
  - "sitedemo"
  - "staticbad"
  - "staticsite"
  - "uidnever"
  - "uidnv2"
  - "winda-demo-08071643"
  - "winda-demo-08071643-api"
