apiVersion: batch/v1
kind: Job
metadata:
  name: "staticdemo-s3-0ms65jf2u002qkwm"
  labels: { app: "staticdemo", workload: "static-deploy", staticSite: "site" }
spec:
  backoffLimit: 1
  template:
    metadata:
      labels: { app: "staticdemo", workload: "static-deploy", staticSite: "site" }
    spec:
      restartPolicy: Never
      initContainers:
        - name: extract-site
          image: "ghcr.io/stevengga/winda-static-demo:latest"
          command: ["cp"]
          args: ["-a", "/usr/share/nginx/html/.", "/workspace/"]
          volumeMounts:
            - { name: workspace, mountPath: "/workspace" }
      containers:
        - name: upload
          image: "public.ecr.aws/aws-cli/aws-cli:2.27.41"
          args: ["--endpoint-url", "http://minio.minio.svc.cluster.local:9000", "s3", "sync", "/workspace", "s3://winda-static-dev/staticdemo/site/", "--delete", "--only-show-errors"]
          env:
            - { name: "AWS_REGION", value: "us-east-2" }
            - { name: "AWS_DEFAULT_REGION", value: "us-east-2" }
          envFrom:
            - secretRef: { name: "aws-static-credentials" }
          volumeMounts:
            - { name: workspace, mountPath: "/workspace", readOnly: true }
      volumes:
        - name: workspace
          emptyDir: {}
