apiVersion: apps/v1
kind: Deployment
metadata:
  name: "verify1-main"
  labels: { app: "verify1", deployment: "main" }
spec:
  replicas: 1
  selector:
    matchLabels: { app: "verify1", deployment: "main" }
  template:
    metadata:
      labels: { app: "verify1", deployment: "main" }
      annotations: { winda.deploy/env-checksum: "a8d1b370165b89b1" }
    spec:
      containers:
        - name: "verify1"
          image: "docker.io/nginx:1.27-alpine"
          ports:
            - containerPort: 80
          env:
            - { name: "DEPLOYMENT", value: "main" }
          envFrom:
            - configMapRef: { name: "verify1-main-env" }
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: "verify1-main"
spec:
  selector: { app: "verify1", deployment: "main" }
  ports:
    - port: 80
      targetPort: 80
